name: absensi_online
description: A Flutter app for online/offline absen
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  package_info_plus: ^8.3.1
  provider: ^6.0.6
  dio: ^5.9.0
  location: ^7.0.1
  another_flushbar: ^1.12.32
  google_fonts: ^5.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
